### ISSUE TITLE
Support Limited Area Models

### ISSUE THREAD

**Issue by JPXKQX** [ecmwf/anemoi-models#18]
### Is your feature request related to a problem? Please describe.

Limited Area Modelling (LAM) is a use case that reuses much of the functionality of global weather models, such as the model architectures. 

It would be interesting to extend the capabilities of anemoi-models to support LAM.

The main difference with respect to the current use case is that some input nodes are not part of the output state. These nodes are the boundary forcing. 

### Describe the solution you'd like

Define an output mask with the data nodes part of the output state. This output mask can be defined based on:

- A node attribute in the graph
- Simple rule, like all nodes with incoming connections from the encoder. 

### Additional context

This supposes that the LAM data and the boundary forcing are passed together.

### Organisation

ECMWF

**Comment by floriankrb** [comment]
> The main difference with respect to the current use case is that some input nodes are not part of the output state. These nodes are the boundary forcing.

The code doing this would be mainly in the `advance_input` method, right?
 https://github.com/ecmwf/anemoi-training/blob/977c26b94e0e2d4a85b213127377894eb99b456e/src/anemoi/training/train/forecaster.py#L190
And somehow keep an additional mask or mapping to define the boundary. And, this mask/mapping would be constant in time.

**Comment by JPXKQX** [comment]
I close this issue as no changes are needed in anemoi-models to support LAM. A working implementation is available in anemoi-training (feature/limited_area).
https://github.com/ecmwf/anemoi-training/blob/feature/limited_area/src/anemoi/training/train/forecaster.py#L198
