### ISSUE TITLE
[Feature] Flexible Imputer

### ISSUE THREAD

**Issue by JesperDramsch** [ecmwf/anemoi-models#73]
### Is your feature request related to a problem? Please describe.

Currently we have constant Nan masks for efficiency reasons. 

Some data has moving NaNs, which should be filled dynamically. 

### Describe the solution you'd like

A new Preprocessor that fills NaNs in moving targets dynamically. 

### Organisation

ECMWF

**Comment by icedoom888** [comment]
@JesperDramsch You can assign this issue to me
